# Generated by Django 6.0.5 on 2026-05-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participantsession',
            new_name='recruitment_status_887633_idx',
            old_name='recruitment_status_entered_idx',
        ),
        migrations.RenameIndex(
            model_name='participantsession',
            new_name='recruitment_conditi_320443_idx',
            old_name='recruitment_condition_idx',
        ),
    ]
