# Generated by Django 5.2.7 on 2026-07-15 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(Study, title):
    base = slugify(title)[:120] or "study"
    candidate = base
    suffix = 2
    while Study.objects.filter(slug=candidate).exists():
        candidate = f"{base[:112]}-{suffix}"
        suffix += 1
    return candidate


def migrate_existing_sources_to_studies(apps, schema_editor):
    RecruitmentSource = apps.get_model("recruitment", "RecruitmentSource")
    Study = apps.get_model("recruitment", "Study")
    StudyCondition = apps.get_model("recruitment", "StudyCondition")

    for source in RecruitmentSource.objects.filter(study__isnull=True, course_instance__isnull=False):
        course_instance = source.course_instance
        course = course_instance.course
        title = f"{course.title if course else 'Study'} - {course_instance.group_name or 'Participants'}"
        study, created = Study.objects.get_or_create(
            course_instance=course_instance,
            defaults={
                "title": title,
                "slug": _unique_slug(Study, title),
                "description": getattr(course, "description", "") if course else "",
                "version_label": "legacy",
                "status": "active",
            },
        )
        if created:
            study.instructors.add(*list(course_instance.instructors.all()))

        labels = [
            item.strip().lower().replace(" ", "_")[:32]
            for item in (source.condition_labels or "").split(",")
            if item.strip()
        ] or ["default"]
        for index, label in enumerate(dict.fromkeys(labels), start=1):
            StudyCondition.objects.get_or_create(
                study=study,
                label=label,
                defaults={
                    "name": label.replace("_", " ").title(),
                    "order": index * 10,
                },
            )

        source.study = study
        source.save(update_fields=["study"])


def reverse_migrate_existing_sources_to_studies(apps, schema_editor):
    RecruitmentSource = apps.get_model("recruitment", "RecruitmentSource")
    RecruitmentSource.objects.filter(study__isnull=False).update(study=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_module_module_type'),
        ('recruitment', '0004_alter_recruitmentsource_condition_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version_label', models.CharField(blank=True, default='v1.0', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='recruitmentsource',
            options={'ordering': ['study_id', 'course_instance_id', 'platform', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='recruitmentsource',
            name='uniq_recruitment_source_per_instance_platform',
        ),
        migrations.AlterField(
            model_name='recruitmentsource',
            name='course_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_sources', to='courses.courseinstance'),
        ),
        migrations.AddField(
            model_name='study',
            name='course_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='courses.courseinstance'),
        ),
        migrations.AddField(
            model_name='study',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_instructor': True}, related_name='studies_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentsource',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_sources', to='recruitment.study'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentsource',
            constraint=models.UniqueConstraint(condition=models.Q(('study__isnull', True)), fields=('course_instance', 'platform'), name='uniq_recruitment_source_per_instance_platform'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentsource',
            constraint=models.UniqueConstraint(condition=models.Q(('study__isnull', False)), fields=('study', 'platform'), name='uniq_recruitment_source_per_study_platform'),
        ),
        migrations.AddField(
            model_name='studycondition',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='recruitment.study'),
        ),
        migrations.RunPython(migrate_existing_sources_to_studies, reverse_migrate_existing_sources_to_studies),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['status', 'created_at'], name='study_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='studycondition',
            constraint=models.UniqueConstraint(fields=('study', 'label'), name='uniq_study_condition_label'),
        ),
    ]
