# Generated by Django 5.2.7 on 2025-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_course_authoring_password_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kt_groups',
            field=models.JSONField(blank=True, default=list, help_text='KnowledgeTree groups/courses the user belongs to'),
        ),
        migrations.AddField(
            model_name='user',
            name='kt_login',
            field=models.CharField(blank=True, help_text='KnowledgeTree Login/Username', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kt_user_id',
            field=models.IntegerField(blank=True, help_text='KnowledgeTree UserID', null=True, unique=True),
        ),
    ]
