# Generated by Django 5.2.7 on 2025-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_kt_groups_user_kt_login_user_kt_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kt_login',
            field=models.CharField(blank=True, help_text='KnowledgeTree Login/Username (primary identifier)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kt_user_id',
            field=models.IntegerField(blank=True, help_text='KnowledgeTree UserID (from database, may be None if only API used)', null=True, unique=True),
        ),
    ]
