# Generated by Django 5.1.1 on 2025-02-19 17:45

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaliperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructors', models.ManyToManyField(blank=True, limit_choices_to={'is_instructor': True}, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, help_text='Custom identifier for the student group', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('canvas_course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('canvas_assignment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lis_outcome_service_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='courses.course')),
                ('instructors', models.ManyToManyField(blank=True, limit_choices_to={'is_instructor': True}, related_name='course_instances_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course_instance')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lis_result_sourcedid', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_result_sourcedid', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_data', models.JSONField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('platform_name', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('resource_link_id', models.CharField(blank=True, help_text='LTI resource link ID', max_length=255, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.unit')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
            options={
                'unique_together': {('email', 'course_instance')},
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0, help_text='Progress between 0 and 1')),
                ('is_complete', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('first_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('total_duration', models.DurationField(default=datetime.timedelta(0))),
                ('state_data', models.JSONField(blank=True, null=True)),
                ('last_response', models.TextField(blank=True)),
                ('lis_result_sourcedid', models.CharField(blank=True, max_length=255, null=True)),
                ('lis_outcome_service_url', models.URLField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module', 'enrollment')},
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['resource_link_id'], name='courses_mod_resourc_7b6f5a_idx'),
        ),
    ]
