# Generated by Django 5.1.1 on 2025-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='supported_protocols',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
