# Generated by Codex on 2026-04-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_module_provider_id_module_supported_protocols"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ModuleProgressEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("launch", "Launch"), ("progress", "Progress"), ("completion", "Completion"), ("outcome", "Outcome"), ("reopened", "Reopened")], max_length=32)),
                ("source", models.CharField(default="system", max_length=64)),
                ("progress", models.FloatField(default=0.0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course_instance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="progress_events", to="courses.courseinstance")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_events", to="courses.module")),
                ("module_progress", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="courses.moduleprogress")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="module_progress_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="moduleprogressevent",
            index=models.Index(fields=["user", "created_at"], name="courses_mod_user_id_37248b_idx"),
        ),
        migrations.AddIndex(
            model_name="moduleprogressevent",
            index=models.Index(fields=["course_instance", "created_at"], name="courses_mod_course_i_3452c4_idx"),
        ),
        migrations.AddIndex(
            model_name="moduleprogressevent",
            index=models.Index(fields=["event_type", "created_at"], name="courses_mod_event_t_4edc69_idx"),
        ),
    ]
