# Generated by Django 5.2.7 on 2026-04-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_progress_timeline_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moduleprogressevent',
            new_name='courses_mod_user_id_6b95a0_idx',
            old_name='courses_mod_user_id_37248b_idx',
        ),
        migrations.RenameIndex(
            model_name='moduleprogressevent',
            new_name='courses_mod_course__82ff2b_idx',
            old_name='courses_mod_course_i_3452c4_idx',
        ),
        migrations.RenameIndex(
            model_name='moduleprogressevent',
            new_name='courses_mod_event_t_e4e216_idx',
            old_name='courses_mod_event_t_4edc69_idx',
        ),
    ]
