# Generated by Django 5.2.7 on 2026-05-07 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def hydrate_existing_order(apps, schema_editor):
    Unit = apps.get_model('courses', 'Unit')
    Module = apps.get_model('courses', 'Module')

    for course_id in Unit.objects.values_list('course_id', flat=True).distinct():
        for index, unit in enumerate(Unit.objects.filter(course_id=course_id).order_by('id'), start=1):
            Unit.objects.filter(pk=unit.pk).update(order=index * 10)
            for module_index, module in enumerate(Module.objects.filter(unit_id=unit.pk).order_by('id'), start=1):
                Module.objects.filter(pk=module.pk).update(order=module_index * 10)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_courses_mod_user_id_37248b_idx_courses_mod_user_id_6b95a0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('launch', 'Launch'), ('download', 'Download'), ('form_submit', 'Form Submit'), ('unlock_denied', 'Unlock Denied')], default='view', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True)),
                ('allow_resubmission', models.BooleanField(default=False)),
                ('submit_button_label', models.CharField(default='Submit', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('text_value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(choices=[('likert', 'Likert'), ('single_choice', 'Multiple Choice - One Answer'), ('multiple_choice', 'Multiple Choice - Multiple Answers'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer')], max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('likert_min_label', models.CharField(blank=True, default='Strongly disagree', max_length=64)),
                ('likert_max_label', models.CharField(blank=True, default='Strongly agree', max_length=64)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='module',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='course_modules/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('imported', 'Imported Activity'), ('external_link', 'External Link'), ('file', 'Uploaded File'), ('form', 'Form / Survey')], default='imported', max_length=32),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='unlock_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='unlock_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(hydrate_existing_order, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['module_type', 'is_visible'], name='courses_mod_module__013fc3_idx'),
        ),
        migrations.AddField(
            model_name='moduleaccesslog',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_logs', to='courses.courseinstance'),
        ),
        migrations.AddField(
            model_name='moduleaccesslog',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_access_logs', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleaccesslog',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='courses.module'),
        ),
        migrations.AddField(
            model_name='moduleaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleform',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='courses.module'),
        ),
        migrations.AddField(
            model_name='moduleformquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.moduleform'),
        ),
        migrations.AddField(
            model_name='moduleformanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.moduleformquestion'),
        ),
        migrations.AddField(
            model_name='moduleformsubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleformsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.moduleform'),
        ),
        migrations.AddField(
            model_name='moduleformsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleformanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.moduleformsubmission'),
        ),
        migrations.AddIndex(
            model_name='moduleaccesslog',
            index=models.Index(fields=['user', 'created_at'], name='courses_mod_user_id_37a547_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleaccesslog',
            index=models.Index(fields=['course_instance', 'created_at'], name='courses_mod_course__11eaac_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleaccesslog',
            index=models.Index(fields=['module', 'created_at'], name='courses_mod_module__b3cd87_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleaccesslog',
            index=models.Index(fields=['event_type', 'created_at'], name='courses_mod_event_t_fcf45c_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleformquestion',
            index=models.Index(fields=['form', 'order'], name='courses_mod_form_id_605643_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleformsubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='courses_mod_form_id_0e06ab_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleformsubmission',
            index=models.Index(fields=['enrollment', 'submitted_at'], name='courses_mod_enrollm_3d939f_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleformsubmission',
            index=models.Index(fields=['user', 'submitted_at'], name='courses_mod_user_id_a6e21c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleformanswer',
            unique_together={('submission', 'question')},
        ),
    ]
