# Generated by Django 5.2.7 on 2026-05-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_moduleaccesslog_moduleform_moduleformanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('imported', 'Imported Activity'), ('external_link', 'External Link'), ('splice_smart_content', 'SPLICE Smart Learning Content'), ('file', 'Uploaded File'), ('form', 'Form / Survey')], default='imported', max_length=32),
        ),
        migrations.AlterField(
            model_name='moduleprogressevent',
            name='event_type',
            field=models.CharField(choices=[('access', 'Access'), ('launch', 'Launch'), ('progress', 'Progress'), ('completion', 'Completion'), ('outcome', 'Outcome'), ('reopened', 'Reopened')], max_length=32),
        ),
    ]
