# Generated by Django 6.0.5 on 2026-05-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_is_locked_for_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('imported', 'Imported Activity'), ('external_link', 'External Link'), ('splice_smart_content', 'SPLICE Smart Learning Content'), ('file', 'Uploaded File'), ('form', 'Form / Survey')], default='imported', max_length=32),
        ),
    ]
