# Generated by Django 5.2.7 on 2026-05-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_module_module_type_and_more'),
        ('courses', '0007_alter_module_module_type'),
    ]

    operations = [
    ]
