# Generated by Django 5.2.7 on 2026-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20260525_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogressevent',
            name='event_type',
            field=models.CharField(choices=[('launch', 'Launch'), ('progress', 'Progress'), ('completion', 'Completion'), ('outcome', 'Outcome'), ('reopened', 'Reopened')], max_length=32),
        ),
    ]
