# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_moduleprogressevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plugin_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
