# Generated by Django 5.2.7 on 2026-07-10 19:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_normalize_enrollment_code_emails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentcode',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollmentcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('course_instance'), name='courses_enrollmentcode_email_instance_ci_unique'),
        ),
    ]
