# Generated by Django 5.2.7 on 2026-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_enrollmentcode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('imported', 'Imported Activity'), ('external_link', 'External Link'), ('splice_smart_content', 'SPLICE Smart Learning Content'), ('file', 'Uploaded File'), ('form', 'Form / Survey'), ('study_consent', 'Study Consent'), ('study_instructions', 'Study Instructions'), ('study_pretest', 'Study Pretest'), ('study_posttest', 'Study Posttest'), ('study_debrief', 'Study Debrief')], default='imported', max_length=32),
        ),
    ]
