# Generated by Django 5.2.7 on 2026-07-15 18:32

import django.db.models.deletion
from django.db import migrations, models


def backfill_study_progress_context(apps, schema_editor):
    ParticipantSession = apps.get_model("recruitment", "ParticipantSession")
    ModuleProgress = apps.get_model("courses", "ModuleProgress")
    ModuleProgressEvent = apps.get_model("courses", "ModuleProgressEvent")

    for session in ParticipantSession.objects.exclude(enrollment_id__isnull=True).order_by("entered_at", "id"):
        condition = session.condition or ""
        ModuleProgress.objects.filter(enrollment_id=session.enrollment_id).update(
            study_participant_session_id=session.id,
            study_condition=condition,
        )
        ModuleProgressEvent.objects.filter(module_progress__enrollment_id=session.enrollment_id).update(
            study_participant_session_id=session.id,
            study_condition=condition,
        )


def clear_study_progress_context(apps, schema_editor):
    ModuleProgress = apps.get_model("courses", "ModuleProgress")
    ModuleProgressEvent = apps.get_model("courses", "ModuleProgressEvent")
    ModuleProgress.objects.update(study_participant_session_id=None, study_condition="")
    ModuleProgressEvent.objects.update(study_participant_session_id=None, study_condition="")


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_module_module_type'),
        ('recruitment', '0005_study_studycondition_alter_recruitmentsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='study_condition',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='study_participant_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress', to='recruitment.participantsession'),
        ),
        migrations.AddField(
            model_name='moduleprogressevent',
            name='study_condition',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='moduleprogressevent',
            name='study_participant_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress_events', to='recruitment.participantsession'),
        ),
        migrations.RunPython(backfill_study_progress_context, clear_study_progress_context),
    ]
