# Generated by Django 5.2.7 on 2026-07-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_moduleprogress_study_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebranchrule',
            name='required_study_condition',
            field=models.CharField(blank=True, help_text='Optional participant condition label required for this branch rule.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='modulebranchrule',
            index=models.Index(fields=['required_study_condition', 'active'], name='branch_study_cond_idx'),
        ),
    ]
