# Generated by Django 5.2.7 on 2026-07-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_modulebranchrule_required_study_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogressevent',
            name='event_type',
            field=models.CharField(choices=[('launch', 'Launch'), ('iframe_load', 'Iframe Load'), ('tab_blur', 'Tab Blur'), ('tab_focus', 'Tab Focus'), ('progress', 'Progress'), ('completion', 'Completion'), ('outcome', 'Outcome'), ('reopened', 'Reopened')], max_length=32),
        ),
    ]
