# Generated by Django 6.0.5 on 2026-10-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_normalize_legacy_study_form_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticRecommendationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField(default=dict)),
                ('edges', models.JSONField(default=list)),
                ('analysis', models.JSONField(default=dict)),
                ('bindings', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_recommendations', to='courses.course')),
            ],
        ),
    ]
