"""
Django settings for modulearn project.

Generated by 'django-admin startproject' using Django 5.1.
"""

import os
import warnings
from pathlib import Path
from dotenv import load_dotenv


# Suppress deprecation warnings from third-party libraries
warnings.filterwarnings('ignore', category=UserWarning, module='pkg_resources')
warnings.filterwarnings('ignore', category=DeprecationWarning, module='paramiko')
warnings.filterwarnings('ignore', category=DeprecationWarning, module='cryptography')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from project root .env (one level above BASE_DIR)
env_path = BASE_DIR.parent / '.env'
env_loaded = load_dotenv(dotenv_path=env_path)
# Note: Logger is defined later, so we'll log this after logger is initialized

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k7s0j45f+h4q_a%8llu@en)@mnbq&e535btz)ce@%6no0uw&i%'

# SECURITY WARNING: don't run with debug turned on in production!
# Automatic environment detection
def get_debug_setting():
    """
    Automatically detect if we're in development or production environment.
    Returns True for development, False for production.
    """
    # Check for explicit DEBUG environment variable first
    debug_env = os.getenv('DEBUG')
    if debug_env is not None:
        return debug_env.lower() in ('true', '1', 'yes', 'on')
    
    # Check for development indicators
    development_indicators = [
        # Environment variables that indicate development
        os.getenv('DJANGO_DEVELOPMENT'),
        os.getenv('DEVELOPMENT'),
        os.getenv('DEV'),
        
        # Check if running in development mode
        os.getenv('RUNSERVER', '').lower() == 'true',
        
        # Check for common development hostnames
        os.getenv('HOSTNAME', '').lower() in ['localhost', 'dev', 'development'],
        
        # Check if we're running on localhost (common in development)
        os.getenv('SERVER_NAME', '').lower() in ['localhost', '127.0.0.1'],
    ]
    
    # If any development indicator is set, we're in development
    if any(development_indicators):
        return True
    
    # Check for production indicators
    production_indicators = [
        # Environment variables that indicate production
        os.getenv('DJANGO_PRODUCTION'),
        os.getenv('PRODUCTION'),
        os.getenv('PROD'),
        
        # Check for common production environment variables
        os.getenv('ENVIRONMENT', '').lower() == 'production',
        os.getenv('ENV', '').lower() == 'production',
        
        # Check for production hostnames
        'proxy.personalized-learning.org' in os.getenv('HOSTNAME', ''),
        'proxy.personalized-learning.org' in os.getenv('SERVER_NAME', ''),
    ]
    
    # If any production indicator is set, we're in production
    if any(production_indicators):
        return False
    
    # Default to production for safety (more secure)
    return False

DEBUG = get_debug_setting()

import logging
logger = logging.getLogger(__name__)

# Log .env file loading status (now that logger is defined)
if env_loaded:
    logger.info(f"Loaded .env file from: {env_path}")
else:
    logger.warning(f".env file not found at: {env_path} - using defaults or system environment variables")


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'proxy.personalized-learning.org',
]

# Application definition
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    # Your apps
    'modulearn',
    'accounts',
    'courses',
    'dashboard',
    'main',
    'lti'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lti.middleware.LTIAuthMiddleware',
]

ROOT_URLCONF = 'modulearn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'modulearn.wsgi.application'

# store db outside of the project
os.makedirs(BASE_DIR / '../modulearn-storage/db', exist_ok=True)

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / '../modulearn-storage/db/db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# Handle static files differently for local development vs production
if DEBUG:
    # In development, serve static files without the /modulearn prefix
    STATIC_URL = '/static/'
else:
    # In production, use the /modulearn-static/ prefix
    STATIC_URL = '/modulearn-static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/modulearn/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'

# Custom Authentication Backends
AUTHENTICATION_BACKENDS = [
    'accounts.backends.KnowledgeTreeBackend',  # KnowledgeTree authentication
    'django.contrib.auth.backends.ModelBackend',  # Default Django authentication
]

# KnowledgeTree Authentication Configuration
KNOWLEDGETREE = {
    'AUTH_ENABLED': os.getenv('KT_AUTH_ENABLED', 'True').lower() == 'true',
    'AUTH_METHOD': os.getenv('KT_AUTH_METHOD', 'api'),  # 'api', 'database', or 'both'
    'AUTH_FALLBACK': os.getenv('KT_AUTH_FALLBACK', 'True').lower() == 'true',
    'API_URL': os.getenv('KT_API_URL', 'http://adapt2.sis.pitt.edu'),
    'API_TIMEOUT': int(os.getenv('KT_API_TIMEOUT', '10')),
    'SECURITY_CHECK_PATH': os.getenv('KT_SECURITY_CHECK_PATH', '/kt/content/j_security_check'),  # Path to j_security_check (legacy, not currently used)
}

# PAWS MySQL Database Configuration (single database server with multiple schemas)
# This database contains both KnowledgeTree (portal_test2 schema) and Aggregate (aggregate schema) data
PAWS_DATABASE = {
    # Database connection (use 'host.docker.internal' if MySQL is on Docker host, or direct IP if on same server)
    'HOST': os.getenv('PAWS_DB_HOST', '127.0.0.1'),
    'PORT': int(os.getenv('PAWS_DB_PORT', '3306')),
    'USER': os.getenv('PAWS_DB_USER', ''),
    'PASSWORD': os.getenv('PAWS_DB_PASSWORD', ''),
    # Schema names (databases on the same MySQL server)
    'KNOWLEDGETREE_SCHEMA': os.getenv('PAWS_DB_KT_SCHEMA', 'portal_test2'),
    'AGGREGATE_SCHEMA': os.getenv('PAWS_DB_AGGREGATE_SCHEMA', 'aggregate'),
    # SSH Tunnel configuration (only needed if MySQL is on a remote server)
    'SSH_HOST': os.getenv('PAWS_DB_SSH_HOST', ''),
    'SSH_PORT': int(os.getenv('PAWS_DB_SSH_PORT', '22')),
    'SSH_USER': os.getenv('PAWS_DB_SSH_USER', ''),
    'SSH_PASSWORD': os.getenv('PAWS_DB_SSH_PASSWORD', ''),
    'SSH_KEY_PATH': os.getenv('PAWS_DB_SSH_KEY_PATH', ''),
    'USE_SSH': os.getenv('PAWS_DB_USE_SSH', 'False').lower() == 'true',  # Only True if MySQL is on remote server
}

# Auto-detect if SSH should be used if credentials are provided but USE_SSH is False
# Note: If MySQL is on the same server as Docker, use host.docker.internal (or host IP) and set USE_SSH=False
if not PAWS_DATABASE['USE_SSH'] and PAWS_DATABASE.get('SSH_HOST') and PAWS_DATABASE.get('SSH_USER'):
    logger.warning(f"SSH credentials provided (SSH_HOST={PAWS_DATABASE['SSH_HOST']}, SSH_USER={PAWS_DATABASE['SSH_USER']}) "
                  f"but PAWS_DB_USE_SSH is False. If MySQL is on the same server, use host.docker.internal and set USE_SSH=False. "
                  f"If MySQL is remote, set PAWS_DB_USE_SSH=True to enable SSH tunneling.")

# Legacy compatibility - map to old structure if needed
if KNOWLEDGETREE['AUTH_METHOD'] in ('database', 'both'):
    KNOWLEDGETREE['DATABASE'] = PAWS_DATABASE

AGGREGATE = {
    'DATABASE': PAWS_DATABASE,
}

# Log database configuration status (without sensitive data) at startup
# This is done here because logger and PAWS_DATABASE are now both defined
try:
    db_config = PAWS_DATABASE
    logger.info(f"PAWS Database Config - USE_SSH: {db_config['USE_SSH']}, "
                f"HOST: {db_config['HOST']}, PORT: {db_config['PORT']}, "
                f"SSH_HOST: {db_config['SSH_HOST'] or 'Not set'}, "
                f"SSH_USER: {db_config['SSH_USER'] or 'Not set'}, "
                f"USER: {db_config['USER'][:3] + '...' if db_config['USER'] else 'Not set'}")
except Exception:
    pass  # Skip if there's any issue

# Database configuration for KnowledgeTree (if using direct database access)
if KNOWLEDGETREE['AUTH_METHOD'] in ('database', 'both'):
    KNOWLEDGETREE['DATABASE'] = {
        'HOST': os.getenv('KT_DB_HOST', ''),
        'PORT': int(os.getenv('KT_DB_PORT', '3306')),
        'NAME': os.getenv('KT_DB_NAME', ''),
        'USER': os.getenv('KT_DB_USER', ''),
        'PASSWORD': os.getenv('KT_DB_PASSWORD', ''),
    }

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',  # OAuth2 authentication
        'rest_framework.authentication.SessionAuthentication',          # Session authentication
        # Add other authentication classes if needed
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Require authentication by default
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',       # Render responses in JSON
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# OAuth2 Provider Settings (using django-oauth-toolkit)
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # Access token lifespan
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,
    'ROTATE_REFRESH_TOKEN': True,
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
        'lti': 'LTI scope',
    },
}

# CORS Headers Configuration
CORS_ALLOWED_ORIGINS = [
    'https://canvas.instructure.com',
    'https://saltire.lti.app',
]

# Security Settings
# SECURE_SSL_REDIRECT = not DEBUG          # Redirect HTTP to HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG        # Secure cookies in production
CSRF_COOKIE_SECURE = not DEBUG           # Secure CSRF cookies in production
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,  # Set to False to prevent duplicate logging
        },
        'courses': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,  # Set to False to prevent duplicate logging
        },
        'dashboard': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'modulearn.dashboard.db_queries': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'       # Replace with your email host
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@example.com'     # Replace with your email
EMAIL_HOST_PASSWORD = 'your-email-password'    # Replace with your email password

LOGIN_URL = 'accounts:login'

# LTI 1.3 Configuration
LTI_CONFIG = {
    'https://saltire.lti.app/platform': {
        'client_id': 'saltire.lti.app',
        'auth_login_url': 'https://saltire.lti.app/platform/auth',
        'auth_token_url': 'https://saltire.lti.app/platform/token/3b4f2aae79ac1d451a4911ac3bc00145',
        'key_set_url': 'https://saltire.lti.app/platform/jwks/3b4f2aae79ac1d451a4911ac3bc00145',
        'auth_audience': 'https://saltire.lti.app/platform',
        'deployment_ids': ['6eb84c059ff928e88f0b734420330efa09905105'],
        'public_key_file': './modulearn/public.key',
        'private_key_file': './modulearn/private.key',
    }
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Allow session cookies to be sent in cross-site requests
SESSION_COOKIE_SAMESITE = 'None'  # Required for iframe embedding
SESSION_COOKIE_SECURE = True      # Required when SameSite is None
CSRF_COOKIE_SAMESITE = 'None'    # Required for iframe embedding
CSRF_COOKIE_SECURE = True        # Required when SameSite is None

# Allow CSRF cookies in cross-site requests (if needed)
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = True

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Configuration for acting as an LTI tool consumer
LTI_CONSUMER_CONFIG = {
    'client_id': 'external-tool-client-id',
    'public_key_file': './modulearn/public.key',
    'private_key_file': './modulearn/private.key',
    # Add any other necessary configuration specific to the external tool
}

def get_primary_domain():
    """Returns the primary domain to use for the application"""
    if DEBUG:
        return "http://localhost:8000"
    return "https://proxy.personalized-learning.org"

LTI_TOOL_CONFIG = {
    'title': 'ModuLearn',
    'description': 'A multi-protocol eLearning module bundling and delivery platform',
    'launch_url': f'{get_primary_domain()}/lti/launch/',
    'custom_fields': {
        'canvas_course_id': '$Canvas.course.id',
        'canvas_user_id': '$Canvas.user.id'
    },
    'extensions': [
        {
            'platform': 'canvas.instructure.com',
            'settings': {
                'text': 'ModuLearn',
                'icon_url': f'{get_primary_domain()}{STATIC_URL}img/logo_128.png',
                'selection_height': 800,
                'selection_width': 1200,
                'privacy_level': 'public'
            }
        }
    ]
}

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://proxy.personalized-learning.org',
]

# LTI 1.1 Configuration
LTI_11_CONSUMER_KEY = 'modulearn_key'
LTI_11_CONSUMER_SECRET = 'modulearn_secret'

# Only force script name in production (not in development)
if not DEBUG:
    FORCE_SCRIPT_NAME = '/modulearn'
USE_X_FORWARDED_HOST = True

# LTI tools: env var names for key/secret/launch base
LTI_TOOL_ENVS = {
    "codecheck": ("CODECHECK_KEY", "CODECHECK_SECRET", "CODECHECK_LAUNCH"),
    "codelab": ("CODELAB_KEY", "CODELAB_SECRET", "CODELAB_LAUNCH"),
    "codeocean": ("CODEOCEAN_KEY", "CODEOCEAN_SECRET", "CODEOCEAN_LAUNCH"),
    "codeworkout": ("CODEWORKOUT_KEY", "CODEWORKOUT_SECRET", "CODEWORKOUT_LAUNCH"),
    "ctat": ("CTAT_KEY", "CTAT_SECRET", "CTAT_LAUNCH"),
    "dbqa": ("DBQA_KEY", "DBQA_SECRET", "DBQA_LAUNCH"),
    "opendsa_problems": ("OPENDSA_PROBLEMS_KEY", "OPENDSA_PROBLEMS_SECRET", "OPENDSA_PROBLEMS_LAUNCH"),
    "opendsa_slideshows": ("OPENDSA_SLIDESHOWS_KEY", "OPENDSA_SLIDESHOWS_SECRET", "OPENDSA_SLIDESHOWS_LAUNCH"),
    # add more as needed
}

# Tool-specific URL builders (only when base URL needs transformation)
def LTI_URL_BUILDER(tool: str, base: str, sub: str) -> str:
    if tool == "ctat":
        return f"{base.rstrip('/')}/mg_{sub}"
    if tool in ("opendsa_problems", "opendsa_slideshows"):
        return f"{base}?custom_ex_settings=%7B%7D&custom_ex_short_name={sub}"
    # default: use base as-is; Node code often passes all context via POST body anyway
    return base

# Optional: tight proxy allowlist (HTTP origins you're willing to fetch)
PROXY_ALLOWED_HOSTS = {
    "columbus.exp.sis.pitt.edu",
    "pawscomp2.sis.pitt.edu",
    "adapt2.sis.pitt.edu",
    "localhost",
    "127.0.0.1",
}
PROXY_MAX_BYTES = 5 * 1024 * 1024
PROXY_CORS_ORIGIN = 'https://proxy.personalized-learning.org'