# Generated by Django 5.2.7 on 2025-12-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTILaunchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('tool', models.CharField(help_text="Tool identifier (e.g., 'codecheck', 'ctat')", max_length=64)),
                ('usr', models.CharField(help_text='User identifier', max_length=255)),
                ('grp', models.CharField(help_text='Group/context identifier', max_length=255)),
                ('sub', models.CharField(help_text='Activity/resource identifier', max_length=512)),
                ('cid', models.CharField(blank=True, default='', help_text='Course ID', max_length=255)),
                ('sid', models.CharField(blank=True, default='', help_text='Session ID', max_length=255)),
                ('svc', models.CharField(blank=True, default='', help_text='Service identifier', max_length=255)),
                ('launch_url', models.URLField(blank=True, default='', help_text='Resolved launch URL (for debugging)', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires')),
            ],
            options={
                'verbose_name': 'LTI Launch Cache',
                'verbose_name_plural': 'LTI Launch Cache Entries',
                'indexes': [models.Index(fields=['tool', 'usr', 'grp'], name='lti_ltilaun_tool_70f975_idx'), models.Index(fields=['expires_at'], name='lti_ltilaun_expires_7d184e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LTIOutcomeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=512)),
                ('tool', models.CharField(blank=True, default='', max_length=64)),
                ('score_raw', models.CharField(help_text='Raw score string from tool', max_length=64)),
                ('score_normalized', models.FloatField(blank=True, help_text='Normalized score (0.0-1.0)', null=True)),
                ('success', models.BooleanField(default=False)),
                ('um_url', models.URLField(blank=True, default='', help_text='UM service URL called', max_length=2048)),
                ('um_response_status', models.IntegerField(blank=True, help_text='HTTP status from UM service', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LTI Outcome Log',
                'verbose_name_plural': 'LTI Outcome Logs',
                'indexes': [models.Index(fields=['source_id'], name='lti_ltioutc_source__623f79_idx'), models.Index(fields=['received_at'], name='lti_ltioutc_receive_4b6bb6_idx'), models.Index(fields=['tool', 'received_at'], name='lti_ltioutc_tool_91b59a_idx')],
            },
        ),
    ]
