# Generated by Django 5.2.7 on 2025-12-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0001_lti_launch_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltilaunchcache',
            name='course_instance_id',
            field=models.IntegerField(blank=True, help_text='CourseInstance.id (parsed from grp)', null=True),
        ),
        migrations.AddField(
            model_name='ltilaunchcache',
            name='module_id',
            field=models.IntegerField(blank=True, help_text='Module.id for progress updates', null=True),
        ),
        migrations.AddField(
            model_name='ltilaunchcache',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='Django User.id (parsed from usr)', null=True),
        ),
        migrations.AlterField(
            model_name='ltilaunchcache',
            name='grp',
            field=models.CharField(help_text='Group ID (CourseInstance ID)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltilaunchcache',
            name='sub',
            field=models.CharField(help_text='Activity identifier from tool URL', max_length=512),
        ),
        migrations.AlterField(
            model_name='ltilaunchcache',
            name='usr',
            field=models.CharField(help_text='User ID (Django auth user ID)', max_length=255),
        ),
    ]
